### ISSUE TITLE
Problem with aframe 1.4.1 & Quest 2

### ISSUE THREAD

**Issue by Mrbside** [stemkoski/A-Frame-Examples#12]
The example quest-physics.html gives this error with Aframe 1.4.0

physics.js:666 Uncaught TypeError: Cannot read properties of undefined (reading 'clamp')
    at i.tock (physics.js:666:36)
    at bind.js:12:17
    at i.tock (index.js:127:7)
    at v.tock (a-scene.js:725:36)
    at e.object3D.onAfterRender (a-scene.js:52:34)
    at hl.render (three.module.js:28497:39)
    at v.render (a-scene.js:751:14)
    at bind.js:12:17
    at three.module.js:28350:35
    at r (three.module.js:12556:3)

**Comment by Mrbside** [comment]
Shane from SideQuest told me in the discord server;

Looks like stemkoski needs to update the example. They need to change THREE.Math to THREE.MathUtils on line 666 of physics.js in that example.

hope this helps

**Comment by Mrbside** [comment]
I can confirm that change in line 666 of physics.js solves the problem, but now the cylinder on the touch controls is in another position, cool thing about aframe 1.4.0 is now the buttons on the touch controls give visual feedback when touched or pressed.

![322389152_845119820089881_2902298479236433942_n](https://user-images.githubusercontent.com/9389898/209627532-a7e3f85f-f20f-4711-9f01-94b522100191.jpg)

**Comment by Mrbside** [comment]
I am now using aframe 1.4.1 & Quest 2

Everything works fine with the same fix on physics.js and the offset of cylinder with raycast on controller

**Comment by Mrbside** [comment]
I also noticed sometimes when the scene just started if I press something on the controller I get errors like this one, on different buttons 
![Untitled-1](https://user-images.githubusercontent.com/9389898/210980471-98a6b8e3-1a51-4d93-ba9a-0d519e02fcd9.jpg)
